######################################################################
# Automatically generated by qmake (2.01a) dom out 20 16:57:25 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
