######################################################################
# Automatically generated by qmake (2.01a) dom out 20 17:59:29 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . nbproject/private
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h
SOURCES += main.cpp \
           MainWindow.cpp \
           nbproject/private/c_standard_headers_indexer.c \
           nbproject/private/cpp_standard_headers_indexer.cpp
